services:
  - type: web
    name: airline-satisfaction-api
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
